package cp.week9;

/**
 *
 * @author Fabrizio Montesi <fmontesi@imada.sdu.dk>
 */
public class Exercise16
{
	/*
	- From Exercise15, use submit(Callable) at the executor to get a Future
	  that returns a result. The result should be the sum of the numbers
	  generated by the producer in that specific product.
	- Put all the futures in a shared list (remember about thread-safety!).
	- When the main thread is done waiting for both producers and consumers
	  to terminate, print out the results in the futures in the shared list.
	*/
}
